[toolchain]
channel = "stable"
targets = [
    # Linux
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    # Windows
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    # macOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
components = ["clippy", "rustfmt", "llvm-tools"]
